Accounting:
  children:
    db_servers:
      hosts:
        DB:
          ansible_host: 3.38.192.168
    lb_servers:
      hosts:
        LB:
          ansible_host: 43.201.16.134
    web_servers:
      hosts:
        WEB:
          ansible_host: 43.202.47.20
  vars:
    ansible_ssh_private_key_file: ~/akamai-assignment/terraform/modules/security/terraform-generated-key.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    ansible_user: ubuntu
    app_name: Test
    db_port: 27017
    db_servers:
    - 192.168.0.13
    lb_port: 80
    web_server_port: 8080
    web_servers:
    - 192.168.0.12