---
  - name: Allow 27017 in iptables
    iptables:
      chain: INPUT
      protocol: tcp
      match: tcp
      destination_port: "27017"
      jump: ACCEPT
    become: yes

  - name: Install package
    apt:
      name: mongodb
      update_cache: yes
      state: present

  - name: Edit mongodb.conf
    replace:
      path: /etc/mongodb.conf
      regexp: '^bind_ip = 127.0.0.1'
      replace: '#bind_ip = 127.0.0.1'
    notify: restart mongodb